#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packages using pip


# Optionally, you can add more commands or customizations here.pip install flask_cors bs4 1xml pelican markdowm gevent 
